In [5]:
import os
import pandas as pd
from openpyxl import load_workbook
import numpy as np
import matplotlib.pyplot as plt
%matplotlib qt
import pickle
import statsmodels.api as sm
from statsmodels.formula.api import ols
import scipy.stats as stats
import copy
import matplotlib as mpl
import fnmatch

['ac__3_MS', 'ac__4', 'ac__5', 'af__2', 'af__5', 'aq__5_MS', 'aq__2', 'aq__4', 'bh1__1', 'bh1__3', 'bh2__2', 'cw__1', 'jm__2_MS', 'jm__1', 'jm__4', 'jp__2_MS', 'jp__3', 'kj__2_MS', 'kj__3', 'kj__4', 'kj__5', 'le__2', 'le__3', 'ls1__4_MS', 'ls1__1', 'ls1__2', 'ls2__3_MS', 'ls2__2', 'ls2__4', 'ls2__5', 'mn__4_MS', 'mn__2', 'mn__5', 'no__4_MS', 'no__2', 'no__3', 'ph__1', 'ph__4', 'rh__3_MS', 'rh__1', 'rh__2', 'rh__4', 'ys__1', 'ys__3', 'ys__5']

In [125]:
subject_day = 'rh__4' + '*'

Measure = 'Fixations'
dataFolderName = r'C:\DTU\Data\201901_JanuaryExpt\DataExtracted\Subjects\\30sWindow' + '\\' + Measure



session1Flag = 0

for root, dirs, subfolder in os.walk(dataFolderName):
    
    technique = 'dwell_time'
    
    if not dirs:
        for file in subfolder:
            
            if fnmatch.fnmatch(file, subject_day):
                print(file)

                pathName = root + '\\' + file
                if session1Flag:
                    df2 = pd.read_excel(open(pathName, 'rb'), sheet_name='Sheet1', header=None)
                else:
                    df1 = pd.read_excel(open(pathName, 'rb'), sheet_name='Sheet1', header=None)
                    session1Flag = 1

rh__4__2019-04-11-13-03-50_1.xlsx
rh__4__2019-04-11-13-40-31_2.xlsx

In [126]:
df_combined = [df1, df2]
df = pd.concat(df_combined, ignore_index=True)
df.columns = [Measure]

In [127]:
df1

           0
0   3.126496
1   0.629539
2   0.630342
3   1.059111
4   1.009053
5   0.632194
6   0.997531
7   0.622764
8   0.368954
9   0.384615
10  0.314444
11  0.633333
12  0.845486
13  0.727778
14  0.822549
15  0.638501
16  0.856272
17  0.432184
18  0.403351
19  0.373889
20  0.497585
21  0.675499
22  0.800337
23  0.707190
24  0.685714
25  0.620072
26  0.672358
27  0.614550
28  0.434291
29  0.369333
..       ...
38  0.603457
39  0.583483
40  0.659079
41  0.762037
42  0.330382
43  0.377778
44  0.474074
45  0.679861
46  0.612626
47  0.719883
48  0.827957
49  0.572840
50  0.632791
51  0.874910
52  0.909195
53  0.910345
54  0.894265
55  0.562879
56  0.496212
57  0.275000
58  0.608148
59  0.751429
60  0.598966
61  0.679580
62  0.817647
63  0.723148
64  0.741441
65  0.645503
66  0.617677
67  0.410278

[68 rows x 1 columns]

In [128]:
print(df1.mean(), df1.median(), df1.std(), df1.count())
print(df2.mean(), df2.median(), df2.std(), df2.count())

0    0.679349
dtype: float64 0    0.633075
dtype: float64 0    0.348231
dtype: float64 0    68
dtype: int64
0    0.788448
dtype: float64 0    0.743483
dtype: float64 0    0.272364
dtype: float64 0    28
dtype: int64

In [129]:
plt.plot(df[Measure])

In [56]:
dfFinal = df.replace(250, np.nan)

In [57]:
plt.plot(dfFinal.TimeStamp, dfFinal.TimeLingeringOnKeys)